[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "server"
startCommand = "npm start"

[[services]]  
name = "frontend"
source = "client"
startCommand = "npm run build && npx serve -s build -p $PORT"
